default: &default
 adapter: mysql2
 pool: 5
 timeout: 5000
 encoding: utf8

development:
 <<: *default
 database: billing-demo-app_development
 host: billing-demo-app.railgun
 strict: false
 port: 3306
 username: root
 password:

test:
 <<: *default
 database: billing-demo-app_test
 host: billing-demo-app.railgun
 strict: false
 port: 3306
 username: root
 password:

production:
 <<: *default
